### ISSUE TITLE
Robot path optimization

### ISSUE THREAD

**Issue by MakinoharaShouko** [osrf/rmf_demos#112]
I am encountering a problem of the robot trying to take a wrong path and hits the wall.

When I send a request, the robot seems to be trying to take the optimum path by traveling in a straight line
![image](https://user-images.githubusercontent.com/57300801/89609310-55ed5800-d82c-11ea-997a-0c5f4a8543d6.png)
but it would end up being stuck as the door
![image](https://user-images.githubusercontent.com/57300801/89609354-73babd00-d82c-11ea-9080-1773b5f70cae.png)

I am building a new map and here is [my repo](https://github.com/MakinoharaShouko/rmf_demos/tree/feature/add_lift_demo). I am using the branch `feature/add_lift_demo`.

To reproduce this behavior:
1. Clone the repo into the RMF workspace with rmf_core, rmf_schedule_visualizer, and traffic_editor
2. Do `colcon build`
3. Source the `setup.bash` and run `ros2 launch demos hotel.launch.xml`
4. In the RViZ RMF panel, select fleet ***magni*** and send a loop request from ***guest_pickup2*** to ***table2***

**Comment by MakinoharaShouko** [comment]
I just hanged the demo on for a long time and the robot got itself out of the door, but it took a really long time. I suppose it would be much quicker if it does not try to force itself traveling straight

**Comment by Kevinskwk** [comment]
Hi! I don't think this is due to path optimization, but rather an issue with multi-level nav-graph waypoint indices. In the current `master` branch of `rmf_core`, waypoints are be given indices starting from zero on each level, leading to repetitive waypoint indices across different levels. So unexpected lanes might be created between waypoints, causing the behaviour described.

This issue is fixed in this PR: https://github.com/osrf/rmf_core/pull/139, along with some other supports for multi-level navigation. You can try checking it out and the robot should behave normally :)

**Comment by MakinoharaShouko** [comment]
I tried the branch from the PR and the problem was solved. Thanks!
