### ISSUE TITLE
Demo machine spec

### ISSUE THREAD

**Issue by cwrx777** [osrf/rmf_demos#16]
Hi,

what's a good machine spec for this demo?
Im using Ubuntu on Hyper V with number of vCPU 8, 1GB RAM and it is cant' even show any image in gazebo.

**Comment by aaronchongth** [comment]
Hello! Could you provide more background information, for example, are there any errors or warnings during the launch? 

What do you see in gazebo after the launch (blank world, or something else)? 

Have you tried waiting for a longer period of time? There are some instances where gazebo needs to pull down resources before loading fully, for example models or plugins, however we made sure to provide all required assets locally.

Just in case, have you tried fiddling with the gazebo world once it has finished launching? Since the world is generated during build-time, we have not yet added the feature to specify the view of the scene during launch, so the user camera might just be pointing at an awkward direction while the whole world is behind the camera.

It is rarely a hardware requirement issue, especially when the demo scene is considerably light-weight. Though I was not able to find concrete details, I did find some discussions that might be useful,
* http://answers.gazebosim.org/question/15125/gazebo-system-requirements/
* https://robotics.stackexchange.com/questions/12325/system-requirements-for-gazebo

**Comment by aaronchongth** [comment]
closed without any follow-up
